backgrounds = { path = "backgrounds/", absolute = false }
backups = { path = "backups/", absolute = false }
wt_profile = "AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json" # Relative to $HOME
extensions = ["gif", "png", "jpg", "jpeg"]
mode = "random" # "random" or "cycle"
